config/routes.rb
Rails.application.routes.draw do
  resources :packages
  get 'home/index'
  post 'home/index'
  
  resources :agencies
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'

end

app/models/agency.rb
class Agency < ActiveRecord::Base
	has_many :packages, dependent: :destroy
	belongs_to :user
end

app/models/package.rb
class Package < ActiveRecord::Base
	belongs_to :agency
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :agency, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit

  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:name, :phone, :address)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@a = 0

    #@packages = Package.paginate(page: params[:page], per_page: 2).order('created_at DESC')

    #@packages = Package.paginate(:page => params[:page], :per_page => 3)



  	@agencies = Agency.all

    
    @prices = Package.select(:price).distinct

    @durations = Package.select(:duration).distinct

=begin
    if params[:agency_id]
    	@packages = Package.where(agency_id: params[:agency_id])
    elsif params[:price]
    	@packages = Package.where(price: params[:price])
    elsif params[:duration]
    	@packages = Package.where(duration: params[:duration])
    else
    	@packages = Package.all
    end    
=end

    @selected_agencies = (params[:agency_ids].present? ? params[:agency_ids] : [])
    @selected_prices = (params[:price_ids].present? ? params[:price_ids] : [])
    @selected_durations = (params[:duration_ids].present? ? params[:duration_ids] : [])

    @packages = Package.all 


    if params[:agency_ids]
      @packages = Package.where("agency_id IN (?)", params[:agency_ids])
    end

    if params[:price_ids]
      @packages = Package.where("price IN (?)", params[:price_ids])
    end

    if params[:duration_ids]
      @packages = Package.where("duration IN (?)", params[:duration_ids])
    end

    if params[:agency_ids] && params[:price_ids]
      @packages = Package.where("agency_id IN (?) AND price IN (?)", params[:agency_ids], params[:price_ids])
    end

    if params[:price_ids] && params[:duration_ids]
      @packages = Package.where("price IN (?) AND duration IN (?)", params[:price_ids], params[:duration_ids])  
    end

    if params[:agency_ids] && params[:duration_ids]
      @packages = Package.where("agency_id IN (?) AND duration IN (?)", params[:agency_ids], params[:duration_ids])
    end
    
    if params[:agency_ids] && params[:price_ids] && params[:duration_ids]
      @packages = Package.where("agency_id IN (?) AND price IN (?) AND duration IN (?)", params[:agency_ids], params[:price_ids] ,params[:duration_ids])                     
    end
#binding.pry

    @packages = @packages.paginate(:page => params[:page], :per_page => 3)


  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: [:show, :edit, :update, :destroy]

  # GET /packages
  # GET /packages.json
  def index
    #binding.pry
    if params[:agency_id].present?
      @packages = Package.where(:agency_id=>params[:agency_id])
    else
      @packages = Package.all
    end
  end

  # GET /packages/1
  # GET /packages/1.json
  def show
  end

  # GET /packages/new
  def new
    @package = Package.new
    @agency = Agency.all    
  end

  # GET /packages/1/edit
  def edit

  end

  # POST /packages
  # POST /packages.json
  def create
    #binding.pry
    @package = Package.new(package_params)

    respond_to do |format|
      if @package.save
        format.html { redirect_to @package, notice: 'Package was successfully created.' }
        format.json { render :show, status: :created, location: @package }
      else
        format.html { render :new }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packages/1
  # PATCH/PUT /packages/1.json
  def update
    respond_to do |format|
      if @package.update(package_params)
        format.html { redirect_to @package, notice: 'Package was successfully updated.' }
        format.json { render :show, status: :ok, location: @package }
      else
        format.html { render :edit }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packages/1
  # DELETE /packages/1.json
  def destroy
    @package.destroy
    respond_to do |format|
      format.html { redirect_to packages_url(:agency_id=>params[:agency_id]), notice: 'Package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package
      @package = Package.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_params
      params.require(:package).permit(:name, :price, :image, :duration, :agency_id)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency) do |f| %>
  <% if @agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% @agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencies.each do |agency| %>
      <tr>
        <td><%= agency.name %></td>
        <td><%= agency.phone %></td>
        <td><%= agency.address %></td>
        <td><%= link_to 'Show', agency %></td>
        <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
        <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agency', new_agency_path %>

app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form' %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agency.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @agency.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @agency.address %>
</p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>

app/views/home/index.html.erb
<script type="text/javascript">
  function f1(){
    //alert("Hello");
    document.myform.submit(this.form);
  }
</script>
<%= form_tag(home_index_path, :name=>'myform')  do %>
  <div id="sidemenu">
    
    <table class="table table" border="0">
  <tbody>
    <tr><th width="60%">Agency</th><th><%= link_to "Clear Filter", home_index_path() %></th></tr> 
    <% @agencies.each do |agency| %>
      <tr>
        <td colspan=2>
<%= check_box_tag "agency_ids[]", agency.id, @selected_agencies.include?(agency.id.to_s), :onclick => "javascript: f1();" %><%=agency.name %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<table class="table table" border="0">
  <tbody>
    <tr><th>Price Range</th></tr>  
    <% @prices.each do |price| %>
      <tr>
        <td>
<%= check_box_tag "price_ids[]", price.price, @selected_prices.include?(price.price.to_s), :onclick => "javascript: f1();" %><%=price.price %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<table class="table table" border="0">
  <tbody>
    <tr><th>Duration</th></tr>  
    <% @durations.each do |duration| %>
      <tr>
        <td>
        <%= check_box_tag "duration_ids[]", duration.duration, @selected_durations.include?(duration.duration.to_s), :onclick => "javascript: f1();" %><%=duration.duration %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>


<div id="content">

<div id="my-posts">    
 <table class="table table-bordered" border="0">
  <tbody>
      <tr>
    <% @packages.each do |package| %>
    <% @a = @a +1 %>
        <td width="311" height="200"><h3><%= Agency.find(package.agency_id).name %></h3><center><%= image_tag package.image.url %></center><h2><%= package.name %></h2><p>Price: <%= package.price %></p><p>Duration: <%= package.duration %></p><p>Some description goes here for each package....</p></td>
    <% if @a ==3 %></tr><tr><% end %>
    <% end %>
      </tr>
  </tbody>
</table>
<% end %>
</div>

<div id="with-button">
    <center><%= will_paginate @packages, :params => {:agency_ids => params[:agency_ids],:price_ids => params[:price_ids],:duration_ids => params[:duration_ids] }, renderer: BootstrapPagination::Rails %></center>
</div>

app/views/home/index.js.erb
$('#my-posts').append('<%= j render @packages %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @packages %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelSure</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <%= csrf_meta_tags %>
<style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
#header{
  margin: 1% auto;
  width:90%;
  height: 20%;
  border-left:1px;
}
  
#sidemenu{
  background-color:#CCCCCC;
  margin: 0% 0.5% 1% 5%;
  width:22%;
  height: 60%;
  float: left;  
}
  
#content{
  margin: 0% 5% 1% 0.5%;
  width:67%;
  height: 60%;
  float: left;
}
  
#footer{
  background-color:cyan;
  margin: 0% 5% 1% 5%;
  width:90%;
  height: 16%;
  float: left;
} 
</style>  
</head>
<body>
  <div id="header">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

<% if user_signed_in? %>     
 <% if current_user.role=="admin" %>
 <%= link_to "Admin Dashboard", rails_admin_path %>
 <% elsif current_user.role=="agent" %>
  <%= link_to "Agent Dashboard", packages_path(:agency_id=>Agency.find_by(user_id: current_user)) %>

  <% else %><% current_user.role=="user" %>
  <%= link_to "User Dashboard", root_path %>

 <% end %>
        <li>Logged in as <strong><%= current_user.email %></strong></li>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li> |
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>        
<% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
<% end %>               
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>



  </div>



<%= yield %>

  <div id="footer"></div> 

</body>
</html>